import { jsPDF } from "jspdf";
import {
  ResumeAnalysisResultV2,
  DomainClassification,
} from "@/types";

interface ReportData {
  analysis: ResumeAnalysisResultV2;
  domain: DomainClassification | null;
  fileName: string;
  targetRole: string;
}

/**
 * Generates a PDF report from resume analysis results.
 * Returns a Buffer of the PDF file.
 */
export function generateAnalysisReport(data: ReportData): Buffer {
  const { analysis, domain, fileName, targetRole } = data;
  const doc = new jsPDF();
  let y = 20;

  // ── Header ──
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("Mentora Resume Analysis Report", 20, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`File: ${fileName}`, 20, y);
  y += 6;
  doc.text(`Target Role: ${targetRole}`, 20, y);
  y += 6;
  doc.text(`Generated: ${new Date().toLocaleDateString("en-IN")}`, 20, y);
  y += 6;
  if (domain) {
    doc.text(`Detected Domain: ${domain.primary} (${Math.round(domain.confidence * 100)}% confidence)`, 20, y);
    y += 6;
  }
  y += 8;

  // ── ATS Score ──
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`ATS Score: ${analysis.atsScore}/100`, 20, y);
  y += 10;

  // ── Score Category ──
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const category = analysis.atsScore >= 75 ? "Excellent" : analysis.atsScore >= 50 ? "Good" : analysis.atsScore >= 40 ? "Needs Improvement" : "Poor";
  doc.text(`Category: ${category}`, 20, y);
  y += 10;

  // ── Strengths ──
  if (analysis.strengths.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Strengths", 20, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const s of analysis.strengths.slice(0, 5)) {
      doc.text(`+ ${s.area}: ${s.description}`, 25, y);
      y += 5;
    }
    y += 5;
  }

  // ── Weaknesses ──
  if (analysis.weaknesses.length > 0) {
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Areas to Improve", 20, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const w of analysis.weaknesses.slice(0, 5)) {
      doc.text(`- [${w.severity}] ${w.area}: ${w.suggestion}`, 25, y);
      y += 5;
    }
    y += 5;
  }

  // ── Keywords ──
  const found = analysis.keywordMatches.filter((k) => k.found);
  const missing = analysis.keywordMatches.filter((k) => !k.found);

  if (y > 240) { doc.addPage(); y = 20; }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Keywords: ${found.length}/${analysis.keywordMatches.length} matched`, 20, y);
  y += 7;

  if (missing.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`Missing: ${missing.slice(0, 8).map((k) => k.skill).join(", ")}`, 25, y);
    y += 7;
  }

  // ── Suggestions ──
  if (analysis.smartSuggestions.length > 0) {
    if (y > 230) { doc.addPage(); y = 20; }
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("AI Suggestions", 20, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    for (const s of analysis.smartSuggestions.slice(0, 6)) {
      const line = `[${s.priority}] ${s.suggestion}`;
      const lines = doc.splitTextToSize(line, 165);
      doc.text(lines, 25, y);
      y += lines.length * 4 + 2;
      if (y > 270) { doc.addPage(); y = 20; }
    }
  }

  // ── Footer ──
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by Mentora — AI Career Guide for Tech Students", 20, 285);

  // Return as Buffer
  const output = doc.output("arraybuffer");
  return Buffer.from(output);
}
