import { RoleDefinition } from "@/types";

export const ROLES: RoleDefinition[] = [
  {
    slug: "frontend-developer",
    title: "Frontend Developer",
    category: "Engineering",
    description:
      "Build user-facing web applications using modern frameworks. You'll work with designers to create responsive, accessible, and performant interfaces that millions of users interact with daily.",
    dayInTheLife:
      "Your typical day involves implementing UI designs in React/Next.js, collaborating with designers on component specs, writing unit tests, debugging cross-browser issues, and participating in code reviews. You'll work closely with backend engineers on API integration.",
    demandLevel: "high",
    salaryINR: {
      fresher: "4-8 LPA",
      mid: "10-20 LPA",
      senior: "20-40 LPA",
    },
    skills: [
      { name: "HTML/CSS", category: "language", weight: 0.9, level: "intermediate" },
      { name: "JavaScript", category: "language", weight: 1.0, level: "intermediate" },
      { name: "React", category: "framework", weight: 0.9, level: "intermediate" },
      { name: "TypeScript", category: "language", weight: 0.7, level: "beginner" },
      { name: "Responsive Design", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Git", category: "tool", weight: 0.7, level: "beginner" },
      { name: "Testing", category: "concept", weight: 0.5, level: "beginner" },
      { name: "Performance Optimization", category: "concept", weight: 0.4, level: "beginner" },
      { name: "REST APIs", category: "concept", weight: 0.6, level: "beginner" },
    ],
    careerPath: ["Junior Frontend Dev", "Frontend Developer", "Senior Frontend Dev", "Lead Frontend Engineer", "Frontend Architect"],
    indianCompanies: ["Flipkart", "Swiggy", "Razorpay", "Zerodha", "CRED", "Meesho", "PhonePe"],
    idealInterests: ["Building user interfaces"],
    idealWorkStyle: ["Solo deep work", "Pair programming"],
    idealProblemSolving: ["Creative/visual"],
    idealWorkPreference: ["Consumer-facing products"],
    codingIntensity: 5,
    mathIntensity: 1,
  },
  {
    slug: "backend-developer",
    title: "Backend Developer",
    category: "Engineering",
    description:
      "Design and build the server-side logic, APIs, and database architecture that powers applications. You'll focus on scalability, security, and data integrity.",
    dayInTheLife:
      "You'll design and implement RESTful/GraphQL APIs, write database queries and migrations, set up authentication and authorization, optimize query performance, handle error logging, and work on microservice architecture. You'll collaborate with frontend devs on API contracts.",
    demandLevel: "high",
    salaryINR: {
      fresher: "5-10 LPA",
      mid: "12-25 LPA",
      senior: "25-50 LPA",
    },
    skills: [
      { name: "Python", category: "language", weight: 0.8, level: "intermediate" },
      { name: "Java", category: "language", weight: 0.7, level: "intermediate" },
      { name: "Node.js", category: "framework", weight: 0.8, level: "intermediate" },
      { name: "SQL", category: "language", weight: 0.9, level: "intermediate" },
      { name: "REST APIs", category: "concept", weight: 1.0, level: "intermediate" },
      { name: "Git", category: "tool", weight: 0.7, level: "beginner" },
      { name: "Database Design", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Authentication", category: "concept", weight: 0.6, level: "beginner" },
      { name: "Docker", category: "tool", weight: 0.5, level: "beginner" },
      { name: "System Design", category: "concept", weight: 0.5, level: "beginner" },
    ],
    careerPath: ["Junior Backend Dev", "Backend Developer", "Senior Backend Dev", "Lead Backend Engineer", "Backend Architect"],
    indianCompanies: ["Google India", "Amazon", "Flipkart", "Walmart Labs", "Atlassian", "Paytm", "Ola"],
    idealInterests: ["Building backend systems"],
    idealWorkStyle: ["Solo deep work", "Small team collaboration"],
    idealProblemSolving: ["Algorithmic/logical"],
    idealWorkPreference: ["Internal tools & infrastructure"],
    codingIntensity: 5,
    mathIntensity: 2,
  },
  {
    slug: "fullstack-developer",
    title: "Full-Stack Developer",
    category: "Engineering",
    description:
      "Work across the entire stack — from database to UI. Full-stack developers are versatile engineers who can build complete features end-to-end, making them highly valued in startups and product companies.",
    dayInTheLife:
      "You'll switch between frontend React components and backend API development, design database schemas, integrate third-party services, deploy features, and often take ownership of entire product features from design to production.",
    demandLevel: "high",
    salaryINR: {
      fresher: "5-10 LPA",
      mid: "12-25 LPA",
      senior: "25-45 LPA",
    },
    skills: [
      { name: "JavaScript", category: "language", weight: 1.0, level: "intermediate" },
      { name: "React", category: "framework", weight: 0.8, level: "intermediate" },
      { name: "Node.js", category: "framework", weight: 0.8, level: "intermediate" },
      { name: "SQL", category: "language", weight: 0.7, level: "intermediate" },
      { name: "HTML/CSS", category: "language", weight: 0.7, level: "intermediate" },
      { name: "TypeScript", category: "language", weight: 0.6, level: "beginner" },
      { name: "Git", category: "tool", weight: 0.7, level: "beginner" },
      { name: "REST APIs", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Docker", category: "tool", weight: 0.4, level: "beginner" },
      { name: "Database Design", category: "concept", weight: 0.6, level: "beginner" },
    ],
    careerPath: ["Junior Full-Stack Dev", "Full-Stack Developer", "Senior Full-Stack Dev", "Tech Lead", "Engineering Manager"],
    indianCompanies: ["Razorpay", "Zerodha", "Postman", "BrowserStack", "Freshworks", "Zoho", "Chargebee"],
    idealInterests: ["Building user interfaces", "Building backend systems"],
    idealWorkStyle: ["Small team collaboration"],
    idealProblemSolving: ["Algorithmic/logical", "Creative/visual"],
    idealWorkPreference: ["Consumer-facing products"],
    codingIntensity: 5,
    mathIntensity: 1,
  },
  {
    slug: "devops-engineer",
    title: "DevOps Engineer",
    category: "Infrastructure",
    description:
      "Bridge the gap between development and operations. You'll automate deployments, manage cloud infrastructure, set up CI/CD pipelines, and ensure systems are reliable and scalable.",
    dayInTheLife:
      "You'll write Infrastructure-as-Code with Terraform, configure CI/CD pipelines, monitor system health with Grafana/Prometheus, debug production incidents, optimize cloud costs, manage Kubernetes clusters, and automate repetitive operational tasks.",
    demandLevel: "high",
    salaryINR: {
      fresher: "5-10 LPA",
      mid: "14-28 LPA",
      senior: "28-55 LPA",
    },
    skills: [
      { name: "Linux", category: "tool", weight: 1.0, level: "intermediate" },
      { name: "Docker", category: "tool", weight: 0.9, level: "intermediate" },
      { name: "CI/CD", category: "concept", weight: 0.9, level: "intermediate" },
      { name: "AWS", category: "tool", weight: 0.8, level: "beginner" },
      { name: "Kubernetes", category: "tool", weight: 0.7, level: "beginner" },
      { name: "Python", category: "language", weight: 0.6, level: "beginner" },
      { name: "Bash/Shell", category: "language", weight: 0.8, level: "intermediate" },
      { name: "Git", category: "tool", weight: 0.8, level: "intermediate" },
      { name: "Networking", category: "concept", weight: 0.6, level: "beginner" },
      { name: "Monitoring", category: "concept", weight: 0.5, level: "beginner" },
    ],
    careerPath: ["Junior DevOps Engineer", "DevOps Engineer", "Senior DevOps Engineer", "SRE Lead", "Platform Architect"],
    indianCompanies: ["Amazon", "Microsoft India", "Wipro", "Infosys", "TCS", "HCL", "Nutanix"],
    idealInterests: ["Automating infrastructure"],
    idealWorkStyle: ["Small team collaboration"],
    idealProblemSolving: ["Systematic/process-oriented"],
    idealWorkPreference: ["Internal tools & infrastructure"],
    codingIntensity: 3,
    mathIntensity: 1,
  },
  {
    slug: "cloud-engineer",
    title: "Cloud Engineer",
    category: "Infrastructure",
    description:
      "Design, deploy, and manage cloud infrastructure on platforms like AWS, Azure, or GCP. Cloud engineers ensure applications are scalable, cost-efficient, and secure in the cloud.",
    dayInTheLife:
      "You'll provision cloud resources, design network architectures, implement security policies, optimize cloud spending, migrate on-premise applications to the cloud, and troubleshoot infrastructure issues. You'll work with tools like Terraform, CloudFormation, and cloud-native services.",
    demandLevel: "medium",
    salaryINR: {
      fresher: "5-9 LPA",
      mid: "12-25 LPA",
      senior: "25-50 LPA",
    },
    skills: [
      { name: "AWS", category: "tool", weight: 1.0, level: "intermediate" },
      { name: "Linux", category: "tool", weight: 0.8, level: "intermediate" },
      { name: "Networking", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Docker", category: "tool", weight: 0.7, level: "beginner" },
      { name: "Terraform", category: "tool", weight: 0.7, level: "beginner" },
      { name: "Python", category: "language", weight: 0.6, level: "beginner" },
      { name: "Security", category: "concept", weight: 0.6, level: "beginner" },
      { name: "CI/CD", category: "concept", weight: 0.5, level: "beginner" },
      { name: "Bash/Shell", category: "language", weight: 0.5, level: "beginner" },
    ],
    careerPath: ["Cloud Associate", "Cloud Engineer", "Senior Cloud Engineer", "Cloud Architect", "VP of Infrastructure"],
    indianCompanies: ["Amazon", "Microsoft India", "Google India", "Persistent Systems", "Cognizant", "Accenture"],
    idealInterests: ["Automating infrastructure"],
    idealWorkStyle: ["Small team collaboration", "Solo deep work"],
    idealProblemSolving: ["Systematic/process-oriented"],
    idealWorkPreference: ["Internal tools & infrastructure", "Security & reliability"],
    codingIntensity: 3,
    mathIntensity: 1,
  },
  {
    slug: "qa-engineer",
    title: "QA Engineer / SDET",
    category: "Quality",
    description:
      "Ensure software quality through manual and automated testing. SDETs (Software Development Engineers in Test) write test frameworks, automate test suites, and catch bugs before they reach users.",
    dayInTheLife:
      "You'll write automated test scripts using Selenium/Cypress/Playwright, design test plans, perform exploratory testing, report and track bugs, set up test CI pipelines, and work closely with developers to understand features and edge cases.",
    demandLevel: "medium",
    salaryINR: {
      fresher: "3.5-7 LPA",
      mid: "8-18 LPA",
      senior: "18-35 LPA",
    },
    skills: [
      { name: "Testing", category: "concept", weight: 1.0, level: "intermediate" },
      { name: "Python", category: "language", weight: 0.7, level: "beginner" },
      { name: "JavaScript", category: "language", weight: 0.6, level: "beginner" },
      { name: "Selenium", category: "tool", weight: 0.8, level: "intermediate" },
      { name: "SQL", category: "language", weight: 0.6, level: "beginner" },
      { name: "Git", category: "tool", weight: 0.6, level: "beginner" },
      { name: "CI/CD", category: "concept", weight: 0.5, level: "beginner" },
      { name: "REST APIs", category: "concept", weight: 0.6, level: "beginner" },
      { name: "Communication", category: "soft", weight: 0.5, level: "intermediate" },
    ],
    careerPath: ["QA Analyst", "QA Engineer", "Senior QA / SDET", "QA Lead", "QA Architect / Test Manager"],
    indianCompanies: ["Flipkart", "Amazon", "Infosys", "TCS", "Wipro", "Cognizant", "Mindtree"],
    idealInterests: ["Ensuring quality"],
    idealWorkStyle: ["Small team collaboration", "Pair programming"],
    idealProblemSolving: ["Systematic/process-oriented", "Analytical/data-driven"],
    idealWorkPreference: ["Consumer-facing products", "Internal tools & infrastructure"],
    codingIntensity: 3,
    mathIntensity: 1,
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    category: "Data",
    description:
      "Turn data into actionable insights. Data analysts query databases, build dashboards, and tell data stories that help businesses make better decisions. This role suits people who enjoy analysis over heavy coding.",
    dayInTheLife:
      "You'll write SQL queries to extract data, build dashboards in Tableau or Power BI, perform ad-hoc analyses for stakeholders, clean and transform datasets, present findings in meetings, and identify trends and anomalies in business metrics.",
    demandLevel: "high",
    salaryINR: {
      fresher: "4-8 LPA",
      mid: "8-18 LPA",
      senior: "18-30 LPA",
    },
    skills: [
      { name: "SQL", category: "language", weight: 1.0, level: "intermediate" },
      { name: "Python", category: "language", weight: 0.7, level: "beginner" },
      { name: "Excel", category: "tool", weight: 0.7, level: "intermediate" },
      { name: "Statistics", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Data Visualization", category: "concept", weight: 0.9, level: "intermediate" },
      { name: "Tableau", category: "tool", weight: 0.6, level: "beginner" },
      { name: "Communication", category: "soft", weight: 0.7, level: "intermediate" },
      { name: "Business Acumen", category: "concept", weight: 0.5, level: "beginner" },
    ],
    careerPath: ["Junior Data Analyst", "Data Analyst", "Senior Data Analyst", "Analytics Manager", "Head of Analytics"],
    indianCompanies: ["Flipkart", "Swiggy", "Paytm", "Razorpay", "MakeMyTrip", "Mu Sigma", "Tiger Analytics"],
    idealInterests: ["Working with data"],
    idealWorkStyle: ["Small team collaboration", "Large cross-functional team"],
    idealProblemSolving: ["Analytical/data-driven"],
    idealWorkPreference: ["Data pipelines & insights"],
    codingIntensity: 2,
    mathIntensity: 4,
  },
  {
    slug: "data-engineer",
    title: "Data Engineer",
    category: "Data",
    description:
      "Build and maintain the data infrastructure that powers analytics and machine learning. Data engineers design data pipelines, ETL processes, and data warehouses that handle massive volumes of data.",
    dayInTheLife:
      "You'll build ETL pipelines using Spark/Airflow, design data warehouse schemas, optimize query performance, ensure data quality and consistency, manage data lakes, and work with data scientists and analysts to provide them clean, reliable data.",
    demandLevel: "high",
    salaryINR: {
      fresher: "6-12 LPA",
      mid: "14-28 LPA",
      senior: "28-50 LPA",
    },
    skills: [
      { name: "SQL", category: "language", weight: 1.0, level: "advanced" },
      { name: "Python", category: "language", weight: 0.9, level: "intermediate" },
      { name: "Spark", category: "framework", weight: 0.7, level: "beginner" },
      { name: "Airflow", category: "tool", weight: 0.6, level: "beginner" },
      { name: "AWS", category: "tool", weight: 0.6, level: "beginner" },
      { name: "Database Design", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "ETL", category: "concept", weight: 0.9, level: "intermediate" },
      { name: "Docker", category: "tool", weight: 0.5, level: "beginner" },
      { name: "Git", category: "tool", weight: 0.5, level: "beginner" },
    ],
    careerPath: ["Junior Data Engineer", "Data Engineer", "Senior Data Engineer", "Lead Data Engineer", "Data Architect"],
    indianCompanies: ["Flipkart", "Amazon", "Walmart Labs", "LinkedIn India", "Gojek", "Dream11", "Jio"],
    idealInterests: ["Working with data", "Building backend systems"],
    idealWorkStyle: ["Solo deep work", "Small team collaboration"],
    idealProblemSolving: ["Algorithmic/logical", "Systematic/process-oriented"],
    idealWorkPreference: ["Data pipelines & insights"],
    codingIntensity: 4,
    mathIntensity: 3,
  },
  {
    slug: "ml-engineer",
    title: "ML Engineer",
    category: "Data/AI",
    description:
      "Build and deploy machine learning models at scale. ML engineers bridge the gap between data science research and production systems, turning experimental models into reliable, scalable services.",
    dayInTheLife:
      "You'll train and evaluate ML models, build feature engineering pipelines, deploy models to production using MLOps practices, monitor model performance, optimize inference speed, and collaborate with data scientists on model improvements.",
    demandLevel: "medium",
    salaryINR: {
      fresher: "6-14 LPA",
      mid: "16-35 LPA",
      senior: "35-60 LPA",
    },
    skills: [
      { name: "Python", category: "language", weight: 1.0, level: "advanced" },
      { name: "Machine Learning", category: "concept", weight: 1.0, level: "intermediate" },
      { name: "Statistics", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "TensorFlow/PyTorch", category: "framework", weight: 0.7, level: "beginner" },
      { name: "SQL", category: "language", weight: 0.6, level: "intermediate" },
      { name: "Docker", category: "tool", weight: 0.5, level: "beginner" },
      { name: "Linear Algebra", category: "concept", weight: 0.6, level: "intermediate" },
      { name: "Git", category: "tool", weight: 0.5, level: "beginner" },
      { name: "Data Visualization", category: "concept", weight: 0.4, level: "beginner" },
    ],
    careerPath: ["ML Intern", "ML Engineer", "Senior ML Engineer", "ML Lead", "ML Architect / Research Scientist"],
    indianCompanies: ["Google India", "Microsoft India", "Flipkart", "Amazon", "Ola", "Myntra", "ShareChat"],
    idealInterests: ["Working with data"],
    idealWorkStyle: ["Solo deep work"],
    idealProblemSolving: ["Analytical/data-driven", "Algorithmic/logical"],
    idealWorkPreference: ["Data pipelines & insights"],
    codingIntensity: 4,
    mathIntensity: 5,
  },
  {
    slug: "uiux-designer",
    title: "UI/UX Designer",
    category: "Design",
    description:
      "Design intuitive, beautiful digital experiences. UI/UX designers research user needs, create wireframes and prototypes, design visual interfaces, and ensure products are easy and delightful to use.",
    dayInTheLife:
      "You'll conduct user research and interviews, create wireframes and prototypes in Figma, design component libraries and design systems, run usability tests, present designs to stakeholders, and collaborate with developers on implementation details.",
    demandLevel: "medium",
    salaryINR: {
      fresher: "3.5-7 LPA",
      mid: "8-18 LPA",
      senior: "18-35 LPA",
    },
    skills: [
      { name: "Figma", category: "tool", weight: 1.0, level: "intermediate" },
      { name: "User Research", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Wireframing", category: "concept", weight: 0.9, level: "intermediate" },
      { name: "Visual Design", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Prototyping", category: "concept", weight: 0.7, level: "beginner" },
      { name: "HTML/CSS", category: "language", weight: 0.4, level: "beginner" },
      { name: "Design Systems", category: "concept", weight: 0.5, level: "beginner" },
      { name: "Communication", category: "soft", weight: 0.7, level: "intermediate" },
    ],
    careerPath: ["UI/UX Intern", "UI/UX Designer", "Senior Designer", "Design Lead", "Head of Design"],
    indianCompanies: ["CRED", "Swiggy", "Flipkart", "Razorpay", "Zomato", "Unacademy", "PhonePe"],
    idealInterests: ["Designing experiences"],
    idealWorkStyle: ["Pair programming", "Small team collaboration"],
    idealProblemSolving: ["Creative/visual"],
    idealWorkPreference: ["Consumer-facing products"],
    codingIntensity: 1,
    mathIntensity: 1,
  },
  {
    slug: "product-analyst",
    title: "Product Analyst",
    category: "Product",
    description:
      "Drive product decisions with data. Product analysts work at the intersection of product management and data analytics, helping teams understand user behavior, measure feature impact, and prioritize the product roadmap.",
    dayInTheLife:
      "You'll analyze product metrics and user funnels, run A/B test analyses, build dashboards for product teams, present insights to PMs and leadership, define KPIs for new features, and help prioritize the product backlog based on data.",
    demandLevel: "medium",
    salaryINR: {
      fresher: "5-9 LPA",
      mid: "10-22 LPA",
      senior: "22-40 LPA",
    },
    skills: [
      { name: "SQL", category: "language", weight: 1.0, level: "intermediate" },
      { name: "Python", category: "language", weight: 0.6, level: "beginner" },
      { name: "Statistics", category: "concept", weight: 0.7, level: "intermediate" },
      { name: "Data Visualization", category: "concept", weight: 0.8, level: "intermediate" },
      { name: "Excel", category: "tool", weight: 0.7, level: "intermediate" },
      { name: "Communication", category: "soft", weight: 0.9, level: "intermediate" },
      { name: "Business Acumen", category: "concept", weight: 0.7, level: "intermediate" },
      { name: "A/B Testing", category: "concept", weight: 0.5, level: "beginner" },
    ],
    careerPath: ["Associate Product Analyst", "Product Analyst", "Senior Product Analyst", "Analytics Lead", "Head of Product Analytics"],
    indianCompanies: ["Flipkart", "Swiggy", "Razorpay", "Meesho", "Dream11", "Groww", "Jupiter"],
    idealInterests: ["Working with data"],
    idealWorkStyle: ["Large cross-functional team", "Small team collaboration"],
    idealProblemSolving: ["Analytical/data-driven"],
    idealWorkPreference: ["Consumer-facing products", "Data pipelines & insights"],
    codingIntensity: 2,
    mathIntensity: 3,
  },
  {
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    category: "Security",
    description:
      "Protect organizations from cyber threats. Cybersecurity analysts monitor systems for vulnerabilities, respond to security incidents, implement security policies, and ensure compliance with security standards.",
    dayInTheLife:
      "You'll monitor security alerts and logs, conduct vulnerability assessments, respond to security incidents, review code for security vulnerabilities, implement firewall and access control policies, run penetration tests, and stay updated on emerging threats.",
    demandLevel: "medium",
    salaryINR: {
      fresher: "4-8 LPA",
      mid: "10-22 LPA",
      senior: "22-45 LPA",
    },
    skills: [
      { name: "Networking", category: "concept", weight: 1.0, level: "intermediate" },
      { name: "Linux", category: "tool", weight: 0.9, level: "intermediate" },
      { name: "Security", category: "concept", weight: 1.0, level: "intermediate" },
      { name: "Python", category: "language", weight: 0.6, level: "beginner" },
      { name: "Bash/Shell", category: "language", weight: 0.6, level: "beginner" },
      { name: "Firewalls/IDS", category: "tool", weight: 0.7, level: "beginner" },
      { name: "Cryptography", category: "concept", weight: 0.5, level: "beginner" },
      { name: "Communication", category: "soft", weight: 0.5, level: "intermediate" },
    ],
    careerPath: ["Security Analyst Trainee", "Cybersecurity Analyst", "Senior Security Engineer", "Security Architect", "CISO"],
    indianCompanies: ["TCS", "Infosys", "Wipro", "Paladion", "Quick Heal", "Lucideus", "Accenture"],
    idealInterests: ["Automating infrastructure", "Ensuring quality"],
    idealWorkStyle: ["Solo deep work", "Small team collaboration"],
    idealProblemSolving: ["Systematic/process-oriented", "Algorithmic/logical"],
    idealWorkPreference: ["Security & reliability"],
    codingIntensity: 3,
    mathIntensity: 2,
  },
];

export function getRoleBySlug(slug: string): RoleDefinition | undefined {
  return ROLES.find((r) => r.slug === slug);
}

export function getAllRoleSlugs(): string[] {
  return ROLES.map((r) => r.slug);
}
